Skip advancing externally created physical slots without `restart_lsn`
When a physical replication slot is defined in the DCS but created manually
outside of Patroni, it may lack a reserved restart LSN. This causes
`_ensure_physical_slots()` to fail during slot advancement due to unexpected
`None` values.

The issue can be reproduced like this:

1. Start the primary
2. Start the standby
3. Create a physical replication slot in the standby without reserving the LSN
4. Add that slot to the permanent slots with patronictl edit-config

As soon as the standby attempts to synchronize the LSN, it logs a stack trace
like this:

```
ERROR: Exception when changing replication slots
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/patroni/postgresql/slots.py", line 551, in sync_replication_slots
    self._drop_incorrect_slots(cluster, slots)
  File "/usr/lib/python3.9/site-packages/patroni/postgresql/slots.py", line 416, in _ensure_physical_slots
    value.get('expected_active') is not True and not value['xmin']:
TypeError: '>' not supported between instances of 'int' and 'NoneType'
```

Such failures can prevent all slot synchronization, including for healthy
slots, affecting replication reliability.

This change improves resilience by skipping unmanaged slots without a
`restart_lsn` and logging a clear warning to guide the user toward corrective
action (in general, the user can fix the cluster by dropping the slot, and
by letting Patroni recreate and manage it).

References: PAT-273.

Signed-off-by: Israel Barth Rubio <israel.barth@enterprisedb.com>