Fix a couple of bugs in quorum state machine
1. when evaluating whether there are healty nodes for a leader race
   before demoting we need to take into account quorum requirements.
   Without it the former leader may end up in recovery surounded by
   asynchronous nodes.
2. QuorumStateResolver wasn't correctly handling the case when the
   replica node quickly joined and disconnected, what was resulting in
   the following error:
```
  File "/home/akukushkin/git/patroni/patroni/quorum.py", line 427, in _generate_transitions
    yield from self.__remove_gone_nodes()
  File "/home/akukushkin/git/patroni/patroni/quorum.py", line 327, in __remove_gone_nodes
    yield from self.sync_update(numsync, sync)
  File "/home/akukushkin/git/patroni/patroni/quorum.py", line 227, in sync_update
    raise QuorumError(f'Sync {numsync} > N of ({sync})')
patroni.quorum.QuorumError: Sync 2 > N of ({'postgresql2'})
2025-02-14 10:18:07,058 INFO: Unexpected exception raised, please report it as a BUG
```