Apply suggestion from code review
Add an `or {}` when reading values from `postgresql.bin_name`
configuraiton option.

That is required otherwise if an user set `postgresql.bin_name`
with no values, the current logic of `get_bin_name` would fail.
See an example below:

```
% cat test.yaml
postgresql:
  bin_name:
  bin_dir: /bin/dir
```

```
>>> with open('test.yaml') as f:
...     test = yaml.safe_load(f)
>>> test
{'postgresql': {'bin_name': None, 'bin_dir': '/bin/dir'}}
>>> test.get('postgresql', {}).get('bin_name', {}).get('bin_name', 'bin_name')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'get'
```

That `or {}` logic is already covered on `pgcommand`, only `get_bin_name`
was missing it.

Signed-off-by: Israel Barth Rubio <israel.barth@enterprisedb.com>